---

#- hosts: tag_class_vcs2vcs
- hosts: tag_Name_ffledgling_test
  user: ec2-user
  vars:

  tasks:
    - name: set private_key
      set_fact:
        ansible_ssh_private_key_file: ~/.ssh/ffledgling-keys.pem

    - name: gather facts
      action: ec2_facts
      register: ec2facts

    - name: print info
      debug: var=ec2facts

    - name: get tags
      ec2_tag: 
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        resource: "{{ ec2facts.ansible_facts.ansible_ec2_instance_id }}"
        region: "{{ ec2facts.ansible_facts.ansible_ec2_placement_region }}"
        state: list
      register: ec2tags

    - name: print info
      debug: var=ec2tags

