---

# Warning, this *WILL* remove all pre-existing keys

- name: install ssh keys
  #host: #all by default, be careful.
  remote_user: ec2-user
  copy:
    dest: ~/.ssh/authorized_keys
    src: files/user_keys
    mode: 0600
    directory_mode: 0755

- name: install keys for rsync
  remote_user: ec2-user
  sudo: yes
  sudo_user: vcs2vcs
  copy:
    dest: ~/.ssh/authorized_keys
    src: files/data_keys
    mode: 0600
    directory_mode: 0755
