# Everything copied over from playbooks in https://github.com/hwine/vcs-sync-ops
# and then modified for compatibility
# Changes from originals, noted with reasons inline
---
- name: Base OS steup
  hosts: tag_system_legacy
  remote_user: ec2-user
  sudo: true

  tasks:


    - name: install git; we need git version 1.7.10.1, but use latest
      yum: name=git state=present

    # Required for mercurial (and others) compile
    - name: install gcc; 
      yum: name=gcc state=present

    # Package names changed here for yum
    - name: install python extras
      yum: name={{ item }} state=present
      with_items:
        - python27-pip
        - python27-devel

    - name: install virtualenv 
      pip: name=virtualenv state=present

    # Changed home to /home/vcs2vcs/ instead of /opt/vcs2vcs for better data,
    # code and user-dir separation
    - name: create user
      user:
        name: vcs2vcs 
        createhome: True
        shell: /bin/bash
        state: present

    - name: disable direct login
      command: passwd -l vcs2vcs

    - name: hand over /opt/vcs2vcs to user vcs2vcs
      # Explicitly *not* adding -R incase someone re-runs when there's actually
      # folders from other users in /opt/vcs2vcs, safer option for now
      file: 
        path: /opt/vcs2vcs
        group: vcs2vcs
        owner: vcs2vcs
        state: directory

- name: setup user account
  hosts: tag_system_legacy
  remote_user: ec2-user
  sudo: true
  sudo_user: vcs2vcs

  tasks:
    # Changing venv to lie in ~/ than in /opt/vcs2vcs, differs from vcs-sync-ops
    - name: create venv
      pip:
        virtualenv: ~/venv/hg
        name: "{{ item }}"
      with_items:
        - "http://mercurial.selenic.com/release/mercurial-2.2.1.tar.gz"
        - "dulwich==0.9.8"
        - "argparse==1.2.1"
        - "http://pypi.pub.build.mozilla.org/pub/hg-git-0.4.0-moz2.tar.gz"

    - name: setup directories on data-disk (/opt/vcs2vcs/)
      file:
        path: "/opt/vcs2vcs/{{item}}"
        state: directory
        force: true
        mode: 0755
      with_items:
        - "etc"
        - "logs"
        - "repos"
        - "staging"

    - name: setup symlinks from ~ to data-disk (/opt/vcs2vcs/)
      file:
        src: "/opt/vcs2vcs/{{item}}"
        dest: "~/{{item}}"
        state: link
        force: true
      with_items:
        - "etc"
        - "logs"
        - "repos"
        - "staging"

- name: setup vcs-sync requirements
  hosts: tag_system_legacy
  remote_user: ec2-user
  sudo: true
  sudo_user: vcs2vcs
  tasks:

    # Chnaged default destination from ~vcs2vcs/bin to ~/bin
    - name: install scripts repo
      hg:
        dest: ~/bin
        repo: https://hg.mozilla.org/users/hwine_mozilla.com/repo-sync-tools/
        executable: ~/venv/hg/bin/hg
        force: yes

    - name: install symlinks
      file: src=~/venv/hg/bin/{{ item }} dest=~/bin/{{ item }} state=link force=yes
      with_items:
        - hg
        - python

    # Copy a local bash_profile instead of appending to the existing one,
    # because the existing one already has other things in it.
    - name: copy local bash_profile with PATH changes
      copy:
        dest: ~/.bash_profile
        src: files/bash_profile
        mode: 0644

    - name: setup ssh (part 1/2)
      file: dest=~/.ssh state=directory mode=0700

    - name: setup ssh (part 2/2)
      copy: dest=~/.ssh/config mode=0600 src=files/ssh_config

    - name: install configs repo
      # this should go on data disk
      hg: >
        dest=~/etc
        repo=https://hg.mozilla.org/users/hwine_mozilla.com/repo-sync-configs/
        executable=~/venv/hg/bin/hg
        force=yes
    - name: forward email
      shell: echo asingh+vcs2vcs@mozilla.com >~vcs2vcs/.forward
      args:
        creates: ~vcs2vcs/.forward

    - name: setup cronjobs
      sudo_user: root
      copy: dest=/etc/cron.d/vcs2vcs.cron src=files/legacy_crontab

    - name: setup log rotation
      sudo_user: root
      file: dest=/etc/logrotate.d/logrotate-legacy.conf src=~vcs2vcs/etc/logrotate-legacy.conf state=link

################################################################################
# Works till here ##############################################################
################################################################################
