---
- hosts: localhost
  connection: local # So that is runs directly on local machine instead of over SSH

  vars_files:
    - config.yml
  
  tasks:
    - name: debug vars
      debug: var=instances

    - name: ensure all instances exist
      ec2: 
        exact_count: 1
        group_id: "{{ aws_config.group_id }}"
        image: "{{ aws_config.image }}" #ami-id, where do we get this from?
        instance_type: "{{ item.instance_type }}" # use smallest possible instance type
        key_name: "{{ aws_config.key_name }}" # How to give it the .pem key?
        region: "{{ aws_config.region }}"
        zone: "{{ aws_config.zone }}"
        wait: True
        count_tag:
            name: "{{ item.name }}"
        instance_tags:
            Name: "{{ item.name }}"
            name: "{{ item.name }}"
            system: "{{ item.system }}"
            class: "vcs2vcs"
      with_items: instances

