# This seems to for running everything locally
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ami_id: ami-e7527ed7



  tasks:

    - name: provision instances
      ec2:
        # This is the ec2 module in use
        key_name: ffledgling-keys # How to give it the .pem key?
        #group: ffledgling-test-machines # Not sure what group to put, or what group is
        instance_type: t2.micro # use smallest possible instance type
        region: us-west-2
        image: "{{ ami_id }}" #ami-id, where do we get this from?
        wait: True
        exact_count: 1
        count_tag:
            Name: ansible-test
        instance_tags:
            Name: ansible-test
      register: ec2

    - name: Add instances' public IPs to a host # Use this for bulk management of the instances
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances

- hosts: ec2hosts
  name: configuration
  user: ec2-user
  gather_facts: True

  tasks:

      - name: check NTP service
        service: name=ntpd state=started
