---

# Warning, this *WILL* remove all pre-existing keys

- name: install ssh keys for host access
  remote_user: ec2-user
  copy:
    dest: ~/.ssh/authorized_keys
    src: files/host_user_keys
    mode: 0400
    backup: yes

- name: configure vcs-sync application ssh directory
  remote_user: ec2-user
  become: yes
  become_user: vcs2vcs
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: TEMPORARY install authorized keys for vcs-sync application
  # these keys are only needed during initial setup, and should not be
  # part of a production system. Probably should have some tags.
  remote_user: ec2-user
  become: yes
  become_user: vcs2vcs
  copy:
    dest: ~/.ssh/authorized_keys
    src: files/vcs_sync_user_keys
    mode: 0400
    backup: yes

- name: install known hosts file for vcs-sync application
  remote_user: ec2-user
  become: yes
  become_user: vcs2vcs
  copy:
    dest: ~/.ssh/known_hosts
    src: files/vcs_sync_known_hosts
    mode: 0400
    backup: yes

